In [43]:
import pandas as pd

In [44]:
df = pd.read_csv("Telco_customer_churn.csv")

In [45]:
df.shape

(7043, 33)

In [46]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices

In [47]:
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='str')

In [48]:
# Converting Heading as snake_case

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [37]:
df.columns

Index(['customerid', 'count', 'country', 'state', 'city', 'zip_code',
       'lat_long', 'latitude', 'longitude', 'gender', 'senior_citizen',
       'partner', 'dependents', 'tenure_months', 'phone_service',
       'multiple_lines', 'internet_service', 'online_security',
       'online_backup', 'device_protection', 'tech_support', 'streaming_tv',
       'streaming_movies', 'contract', 'paperless_billing', 'payment_method',
       'monthly_charges', 'total_charges', 'churn_label', 'churn_value',
       'churn_score', 'cltv', 'churn_reason'],
      dtype='str')

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customerid         7043 non-null   str
 1   count              7043 non-null   int64
 2   country            7043 non-null   str
 3   state              7043 non-null   str
 4   city               7043 non-null   str
 5   zip_code           7043 non-null   int64
 6   lat_long           7043 non-null   str
 7   latitude           7043 non-null   float64
 8   longitude          7043 non-null   float64
 9   gender             7043 non-null   str
 10  senior_citizen     7043 non-null   str
 11  partner            7043 non-null   str
 12  dependents         7043 non-null   str
 13  tenure_months      7043 non-null   int64
 14  phone_service      7043 non-null   str
 15  multiple_lines     7043 non-null   str
 16  internet_service   7043 non-null   str
 17  online_security    7043 non-null   str
 18  online_backup      7043 non-null   str
 19  device_protection  7043 non-null   str
 20  tech_support       7043 non-null   str
 21  streaming_tv       7043 non-null   str
 22  streaming_movies   7043 non-null   str
 23  contract           7043 non-null   str
 24  paperless_billing  7043 non-null   str
 25  payment_method     7043 non-null   str
 26  monthly_charges    7043 non-null   float64
 27  total_charges      7043 non-null   float64
 28  churn_label        7043 non-null   str
 29  churn_value        7043 non-null   int64
 30  churn_score        7043 non-null   int64
 31  cltv               7043 non-null   int64
 32  churn_reason       1869 non-null   str
dtypes: float64(4), int64(6), str(23)
memory usage: 1.8 MB

In [50]:
# Check Missing Values

df.isnull().sum()

customerid              0
count                   0
country                 0
state                   0
city                    0
zip_code                0
lat_long                0
latitude                0
longitude               0
gender                  0
senior_citizen          0
partner                 0
dependents              0
tenure_months           0
phone_service           0
multiple_lines          0
internet_service        0
online_security         0
online_backup           0
device_protection       0
tech_support            0
streaming_tv            0
streaming_movies        0
contract                0
paperless_billing       0
payment_method          0
monthly_charges         0
total_charges           0
churn_label             0
churn_value             0
churn_score             0
cltv                    0
churn_reason         5174
dtype: int64

In [51]:
# Percentage of Missing Values

(df.isnull().sum()/len(df)*100).sort_values(ascending= False)

churn_reason         73.463013
customerid            0.000000
count                 0.000000
state                 0.000000
country               0.000000
zip_code              0.000000
lat_long              0.000000
latitude              0.000000
city                  0.000000
gender                0.000000
senior_citizen        0.000000
partner               0.000000
dependents            0.000000
tenure_months         0.000000
phone_service         0.000000
multiple_lines        0.000000
longitude             0.000000
internet_service      0.000000
online_security       0.000000
device_protection     0.000000
online_backup         0.000000
streaming_tv          0.000000
streaming_movies      0.000000
contract              0.000000
tech_support          0.000000
paperless_billing     0.000000
payment_method        0.000000
total_charges         0.000000
monthly_charges       0.000000
churn_label           0.000000
churn_value           0.000000
churn_score           0.000000
cltv                  0.000000
dtype: float64

In [52]:
# Check Duplicate Rows

df.duplicated().sum()

np.int64(0)

In [53]:
# Check Unique Values

for col in df.select_dtypes(include = 'object').columns:
    print(f"\n{col}")
    print(df[col].unique())

customerid
<StringArray>
['3668-QPYBK', '9237-HQITU', '9305-CDSKC', '7892-POOKP', '0280-XJGEX',
 '4190-MFLUW', '8779-QRDMV', '1066-JKSGK', '6467-CHFZW', '8665-UTDHZ',
 ...
 '0871-OPBXW', '3605-JISKB', '9767-FFLEM', '8456-QDAVC', '7750-EYXWZ',
 '2569-WGERO', '6840-RESVB', '2234-XADUH', '4801-JZAZL', '3186-AJIEK']
Length: 7043, dtype: str

country
<StringArray>
['United States']
Length: 1, dtype: str

state
<StringArray>
['California']
Length: 1, dtype: str

city
<StringArray>
[    'Los Angeles',   'Beverly Hills', 'Huntington Park',         'Lynwood',
  'Marina Del Rey',       'Inglewood',    'Santa Monica',        'Torrance',
        'Whittier',        'La Habra',
 ...
      'Janesville',      'Litchfield',        'Loyalton',        'Madeline',
    'Markleeville',         'Milford',         'Calpine',        'Standish',
        'Tulelake',  'Olympic Valley']
Length: 1129, dtype: str

lat_long
<StringArray>
['33.964131, -118.272783',  '34.059281, -118.30742', '34.048013, -118.293953',
 '34.062125, -118.315709', '34.039224, -118.266293', '34.066367, -118.309868',
  '34.02381, -118.156582', '34.066303, -118.435479', '34.099869, -118.326843',
 '34.089953, -118.294824',
 ...
 '40.294034, -120.512622', '40.507272, -120.338228', '39.637471, -120.226338',
 '41.042003, -120.506086',  '38.735789, -119.85798', '40.181279, -120.392967',
 '39.672813, -120.456699', '40.346634, -120.386422', '41.813521, -121.492666',
 '39.191797, -120.212401']
Length: 1652, dtype: str

gender
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

senior_citizen
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

partner
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

dependents
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

phone_service
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

multiple_lines
<StringArray>
['No', 'Yes', 'No phone service']
Length: 3, dtype: str

internet_service
<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

online_security
<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

online_backup
<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

device_protection
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

tech_support
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

streaming_tv
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

streaming_movies
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

contract
<StringArray>
['Month-to-month', 'Two year', 'One year']
Length: 3, dtype: str

paperless_billing
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

payment_method
<StringArray>
[             'Mailed check',          'Electronic check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

churn_label
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

churn_reason
<StringArray>
[             'Competitor made better offer',
                                     'Moved',
             'Competitor had better devices',
 'Competitor offered higher download speeds',
              'Competitor offered more data',
                            'Price too high',
                   'Product dissatisfaction',
                   'Service dissatisfaction',
           'Lack of self-service on Website',
                       'Network reliability',
                 'Limited range of services',
  'Lack of affordable download/upload speed',
                     'Long distance charges',
                        'Extra data charges',
                                'Don't know',
          'Poor expertise of online support',
           'Poor expertise of phone support',
              'Attitude of service provider',
                'Attitude of support person',
                                  'Deceased',
                                         nan]
Length: 21, dtype: str

C:\Users\Administrator\AppData\Local\Temp\ipykernel_14672\72451774.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include = 'object').columns:

Note:

errors = 'coesrce'  --> Finds a number that cannot be converted into a number, it will replace it with NaN

In [54]:
# Check Total Charges

df['total_charges'] = pd.to_numeric( df['total_charges'] , errors = 'coerce')

In [55]:
df['total_charges']

0        108.15
1        151.65
2        820.50
3       3046.05
4       5036.30
         ...
7038    1419.40
7039    1990.50
7040    7362.90
7041     346.45
7042    6844.50
Name: total_charges, Length: 7043, dtype: float64

In [56]:
df['total_charges'].isnull().sum()

np.int64(0)

In [57]:
# Handle Missing Values

df['total_charges'] = df['total_charges'].fillna(0)

In [58]:
df['total_charges'].isnull().sum()

np.int64(0)

In [59]:
df.dtypes

customerid               str
count                  int64
country                  str
state                    str
city                     str
zip_code               int64
lat_long                 str
latitude             float64
longitude            float64
gender                   str
senior_citizen           str
partner                  str
dependents               str
tenure_months          int64
phone_service            str
multiple_lines           str
internet_service         str
online_security          str
online_backup            str
device_protection        str
tech_support             str
streaming_tv             str
streaming_movies         str
contract                 str
paperless_billing        str
payment_method           str
monthly_charges      float64
total_charges        float64
churn_label              str
churn_value            int64
churn_score            int64
cltv                   int64
churn_reason             str
dtype: object

In [60]:
df.describe()

,count,zip_code,latitude,longitude,tenure_months,monthly_charges,total_charges,churn_value,churn_score,cltv
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,2279.734304,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,2266.794470,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,398.550000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,1394.550000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,3786.600000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,8684.800000,1.000000,100.000000,6500.000000

In [61]:
# Check Categorical Consistency

df['gender'].value_counts()

gender
Male      3555
Female    3488
Name: count, dtype: int64

In [62]:
df['contract'].value_counts()

contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [63]:
df['payment_method'].value_counts()

payment_method
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

In [64]:
# Check the Target Variable

df['churn_label'].value_counts()

churn_label
No     5174
Yes    1869
Name: count, dtype: int64

In [65]:
# Percentage of Target Variable

df['churn_label'].value_counts(normalize= True)*100

churn_label
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [66]:
# Check the uniqueness in CustomerID

df['customerid'].nunique()

7043

In [67]:
len(df)

7043

In [68]:
# Validation

print("Rows :", df.shape[0])
print("Columns :", df.shape[1])
print("Duplicates :", df.duplicated().sum())
print("Missing Values :" , df.isnull().sum()[df.isnull().sum() > 0])

Rows : 7043
Columns : 33
Duplicates : 0
Missing Values : churn_reason    5174
dtype: int64

Note :

Index = False :  
    It means don't save the pandas index as an extra column in csv

In [70]:
df.to_csv('Telco_customer_churn.csv', index= False)